dockers:
- image_templates:
  - 'ghcr.io/pl4nty/ipa-web:{{ .Tag }}-amd64'
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
- image_templates:
  - 'ghcr.io/pl4nty/ipa-web:{{ .Tag }}-arm64'
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/arm64"
  goarch: arm64
docker_manifests:
- name_template: 'ghcr.io/pl4nty/ipa-web:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/pl4nty/ipa-web:{{ .Tag }}-amd64'
  - 'ghcr.io/pl4nty/ipa-web:{{ .Tag }}-arm64'