name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: Allow write access to checks to allow the action to annotate code in the PR.
      checks: write
    steps:
    - uses: actions/checkout@v3

    - uses: securego/gosec@master
      with:
        # we let the report trigger content trigger a failure using the GitHub Security features.
        args: '-no-fail -fmt sarif -out results.sarif ./...'
    - uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif

    - uses: actions/setup-go@v5
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - run: go build -v ./...
    - uses: robherley/go-test-action@v0.1.0
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}

